// ---convert type enum: int,float, bool
export default {
  billingDom: 'billingDom',
  isBundled: 'isBundled',
  isDiscountable: 'isDiscountable',
  startDuration: 'startDuration',
  endDuration: 'endDuration',
  startUnit: 'startUnit',
  endUnit: 'endUnit',
  minimumQuantity: 'minimumQuantity',
  maximumQuantity: 'maximumQuantity',
  index: 'index',
  refIndex: 'refIndex',
  amount: 'amount',
  grantDuration: 'grantDuration',
  isQuantityScaleable: 'isQuantityScaleable',
  isQuantityScalable: 'isQuantityScalable',
  validityDuration: 'validityDuration',
  isPartialFulfillmentAllowed: 'isPartialFulfillmentAllowed',
  validityUnit: 'validityUnit',
  initialTerm: 'initialTerm',
  renewalTerm: 'renewalTerm',
  trialTerm: 'trialTerm',
  quantity: 'quantity',
  priceOverride: 'priceOverride',
  priceOffset: 'priceOffset',
  discountPercent: 'discountPercent',
  relativeStart: 'relativeStart',
  relativeEnd: 'relativeEnd',
  netAmount: 'netAmount',
  numberOfTransactions: 'numberOfTransactions',
  percent: 'percent',
};
