export default {
  customerSegment: {
    b2b: 'B2B',
    b2c: 'B2C',
    b2b2c: 'B2B2C',
  },
  accountReason: {
    none: 'NONE',
    paymentFailure: 'PAYMENT_FAILURE',
    customerRequest: 'CUSTOMER_REQUEST',
    collections: 'COLLECTIONS',
    internalControl: 'INTERNAL_CONTROL',
  },
  accountStatus: {
    active: 'ACTIVE',
    inactive: 'INACTIVE',
    closed: 'CLOSED',
  },
  type: {
    directCustomer: 'DIRECT_CUSTOMER',
    partner: 'PARTNER',
    parterCustomer: 'PARTNER_CUSTOMER',
    reseller: 'RESELLER',
    resellerCustomer: 'RESELLER_CUSTOMER',
    internalTestAccount: 'INTERNAL_TEST_ACCOUNT',
    externalTestAccount: 'EXTERNAL_TEST_ACCOUNT',
    brokerChannelPartner: 'BROKER_CHANNEL_PARTNER',
    dataSupplier: 'DATA_SUPPLIER',
    interCompany: 'INTERCOMPANY',
    connectorPartner: 'CONNECTOR_PARTNER',
    affiliate: 'AFFILIATE',
    none: 'NONE',
  },
  subType: {
    silever: 'SILVER',
    gold: 'GOLD',
    platinum: 'PLATINUM',
    none: 'NONE',
  },
  salesChannel: {
    web: 'WEB',
    pos: 'POS',
    ecommerce: 'ECOMMERCE',
    advertisement: 'ADVERTISEMENT',
    teleMarket: 'TELE_MARKET',
    agentCare: 'AGENT_CARE',
    none: 'NONE',
  },
  marketSegment: {
    individal: 'INDIVIDUAL',
    smallEnterprise: 'SMALL_ENTERPRISE',
    smb: 'SMB',
    largeEnterprise: 'LARGE_ENTERPRISE',
    none: 'NONE',
  },
  // -----contact
  roles: {
    billing: 'BILLING',
    payment: 'PAYMENT',
    servide: 'SERVICE',
    soldTo: 'SOLD_TO',
  },
  // salutation: {
  //   mr: 'Mr.',
  //   mss: 'Mss.',
  //   mrs: 'Mrs.',
  // },
  phoneType: {
    work: 'WORK',
    home: 'HOME',
    mobile: 'MOBILE',
    fax: 'FAX',
  },
  // -----billing profile
  billingFrequency: {
    monthly: 'MONTHLY',
    biMonthly: 'BI_MONTHLY',
    quarterly: 'QUARTERLY',
    semiAnnual: 'SEMI_ANNUAL',
    annual: 'ANNUAL',
  },
  invoiceType: {
    summary: 'SUMMARY',
    detail: 'DETAIL',
    dteailSuppress: 'DETAIL_SUPPRESSED',
  },
  invoiceDelivery: {
    download: 'DOWNLOAD',
    email: 'EMAIL',
    mail: 'MAIL',
  },
  // ----- payment profile
  paymentTerm: {
    net30: 'NET_30',
    net45: 'NET_45',
    net60: 'NET_60',
    net75: 'NET_75',
    net90: 'NET_90',
  },
  paymentMethod: {
    check: 'CHECK',
    creditCard: 'CREDIT_CARD',
    nonPaying: 'NON_PAYING',
  },
  // Pricing Manager
  revenueType: {
    transaction: 'TRANSACTION',
    subscription: 'SUBSCRIPTION',
    professionalService: 'PROFESSIONAL_SERVICES',
    laborExpense: 'LABOR_EXPENSE',
    laborTime: 'LABOR_TIME',
    license: 'LICENSE',
  },
  status: {
    create: 'CREATE',
    approve: 'APPROVED',
    sellable: 'SELLABLE',
    nonSellable: 'NON_SELLABLE',
    sunset: 'SUNSET',
  },
  unit: {
    days: 'DAYS',
    weeks: 'WEEKS',
    months: 'MONTHS',
    quarterly: 'QUARTERS',
    years: 'YEARS',
    unbound: 'UNBOUND',
  },
  grantUnit: {
    days: 'DAYS',
    weeks: 'WEEKS',
    months: 'MONTHS',
    quarterly: 'QUARTERS',
    years: 'YEARS',
  },
  pricingModel: {
    flat: 'FLAT',
    flatWithGrants: 'FLAT_WItH_GRANTS',
    tiered: 'TIERED',
    recurring: 'RECURRING',
    recurringWithGrants: 'RECURRING_WITH_GRANTS',
    recurringTiered: 'RECURRING_TIERED',
    transactionAttributeBased: 'TRANSACTION_ATTRIBUTE_BASED',
    customerAttributeBased: 'CUSTOMER_ATTRIBUTE_BASED',
    usageAttributeBase: 'USAGE_ATTRIBUTE_BASED',
    complex: 'COMPLEX',
  },
  transactionType: {
    oneTime: 'ONE_TIME',
    oneTimeCancel: 'ONE_TIME_CANCEL',
    forwardRecurring: 'FORWARD_RECURRING',
    arrearsRecurring: 'ARREARS_RECURRING',
    forwardBilledGrant: 'FORWARD_BILLED_GRANT',
    arrearsBilledGrant: 'ARREARS_BILLED_GRANT',
    usage: 'USAGE',
    billDiscount: 'BILL_DISCOUNT',
    tax: 'TAX',
  },
  serviceType: {
    default: 'DEFAULT',
    voip: 'VOIP',
    cable: 'CABLE',
    utilities: 'UTILITIES',
    retail: 'RETAIL',
    wholesale: 'WHOLESALE',
    wireline: 'WIRELINE',
    telephony: 'TELEPHONY',
    iptv: 'IPTV',
    data: 'DATA',
    professional: 'PROFESSIONAL',
    internet: 'INTERNET',
    homesecurity: 'HOMESECURITY',
  },
  proration: {
    full: 'FULL',
    zero: 'ZERO',
    prorate: 'PRORATE',
  },
  purchaseProration: 'purchaseProration',
  cancelProration: 'cancelProration',
  upgradeProration: 'upgradeProration',
  downgradeProration: 'downgradeProration',
  accountType: 'accountType',
  accountSubType: 'accountSubType',
  dependencyType: {
    mutuallyExclusive: 'MUTUALLY_EXCLUSIVE',
    preRequisite: 'PRE_REQUISITE',
    upgrade: 'UPGRADE',
    downgrade: 'DOWNGRADE',
  },
  billType: {
    regular: 'REGULAR',
    oneTime: 'ONE_TIME',
    regenenrated: 'REGENERATED',
  },
  billStatus: {
    pending: 'PENDING',
    active: 'ACTIVE',
  },
};
